imgix/__init__.py
tests/test_url_builder.py

Running this snippet
```python
builder = imgix.UrlBuilder(IMGIX_DOMAIN)
builder.create_url(u'ǝ'.encode('utf8'))
```
returns `http://site.imgix.net/\xc7\x9d` on master. Shouldn't it be returning `http://site.imgix.net/%C7%9D` (as it used to)? :-)

URL does not get encoded correctly

---

imgix/__init__.py
imgix/urlbuilder.py
imgix/urlhelper.py
tests/test_url_builder.py

[Per the imgix-blueprint](https://github.com/imgix/imgix-blueprint#protocols), we should be using HTTPS by default.

Default to HTTPS

---

imgix/compat.py
imgix/urlbuilder.py
imgix/urlhelper.py
tests/test_url_builder.py

This makes usage more consistent, and eliminates any current/future issues with reserved word collisions (e.g. `or`).

Switch `UrlBuilder#create_url` to accept dict instead of kwargs

---

README.md

Hello,
Your README was quite confusing until I dug through the repo history. Hopefully I can help others from being  equally confused. 
[In this commit](https://github.com/imgix/imgix-python/commit/7b19c9c146a2bdeb26494d68bf97334c322cf9c1) args that UrlBuilder accepts changed from kwargs to a dict. This pull fixes the docs.
Cheers,
```
>>> import imgix
>>> builder = imgix.UrlBuilder(["demos-1.imgix.net"])
>>> print builder.create_url("/flower.png", w=100, h=100)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: create_url() got an unexpected keyword argument 'w'
>>> print builder.create_url("/bridge.png", {'w': 100, 'h': 100})
https://demos-1.imgix.net/bridge.png?h=100&w=100&ixlib=python-1.0.0
```

Updating README.md with dict usage not kwargs

---

imgix/urlbuilder.py
tests/test_url_builder.py

If you pass a tuple of domains to the URLBuilder, an error is raised after a call to `create_url` that doesn't point to the culprit very clearly:
```python
File "/Users/tommi/.virtualenvs/project/lib/python2.7/site-packages/django_imgix/templatetags/imgix_tags.py", line 186, in get_imgix
url = builder.create_url(image_url, arguments)
File "/Users/tommi/.virtualenvs/project/lib/python2.7/site-packages/imgix/urlbuilder.py", line 58, in create_url
return str(url_obj)
File "/Users/tommi/.virtualenvs/project/lib/python2.7/site-packages/imgix/urlhelper.py", line 116, in __str__
"", ])
File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 231, in urlunparse
return urlunsplit((scheme, netloc, url, query, fragment))
File …
```

Accept a tuple of domains

---

imgix/urlhelper.py
tests/test_url_helper.py

Ensure parameters aren't deleted if the associated value
is None or False.

Don't delete parameters if value is None or False

---

imgix/urlbuilder.py
imgix/urlhelper.py
tests/test_url_builder.py
tests/test_url_helper.py

Deprecate opts kwarg from UrlHelper and UrlBuilder
classes in favor of params kwarg.

Deprecate opts kwarg in favor of params

---

imgix/urlbuilder.py
imgix/urlhelper.py
tests/test_url_builder.py
tests/test_url_helper.py

Renames the parameter used during `UrlBuilder` initialization for signing with the library name and version. Any attempt to pass in the previous parameter (`sign_with_library_version`) will raise a deprecation warning.

Rename `sign_with_library_version` to `include_library_param`

---

README.rst
imgix/urlbuilder.py
tests/test_url_builder.py

This PR begins the process of deprecating, and eventually removing, domain sharding from the imgix-python library.
The `UrlBuilder` object will now throw a warning when users attempt to initialize it by passing in multiple domains in the form of a list or tuple.

fix: deprecate domain sharding

---

README.rst

This PR adds a link in the README to the [blog post](https://blog.imgix.com/2019/05/03/deprecating-domain-sharding), explaining the decision to remove the domain sharding feature from the imgix SDK.
Relates to #41

docs: add link to domain sharding deprecation blog post

---

README.rst

This PR corrects a malformed rst hyperlink in #42 
Relates to #41

 format: correct malformed hyperlink is rst 

---

README.rst
imgix/urlbuilder.py
tests/test_url_builder.py

This PR adds a new parameter/field `domain` to `UrlBuilder`, as part of the transition to remove domain sharding (and with it, `domains`).

feat: deprecate `domains` in favor of `domain`

---

README.rst
imgix/constants.py
imgix/urlbuilder.py
tests/test_srcset.py

This PR adds a new function to the imgix-python interface that will either generate a width descriptor or DPR `srcset` based on the specified parameters.
Also corrects how the `params` argument is initialized in `create_url()` to prevent potential bizarre behavior.

feat: add srcset generation

---

.coveragerc
tests/test_url_builder.py
tests/test_url_helper.py
tox.ini

This PR modifies the `tox` configuration to improve the accuracy of code coverage reports. It also adds parallel testing of python2 and python3.
Run command `tox`
Before:
```
============= test session starts =============
platform darwin -- Python 3.7.3, pytest-5.1.1, py-1.8.0, pluggy-0.12.0
cachedir: .tox/core/.pytest_cache
plugins: cov-2.7.1
collected 61 items
tests/test_srcset.py .................                           [ 27%]
tests/test_url_builder.py .......................                [ 65%]
tests/test_url_helper.py .....................                   [100%]
Coverage.py warning: No data was collected. (no-data-collected)
-------------------- coverage: platform darwin, python 3.7.3-final-0 --------------------
Name                  Stmts   Miss  Cover …
```

build(tox): improve code coverage reporting; parallelize testing

---

README.rst
imgix/constants.py
imgix/urlbuilder.py
tests/test_srcset.py

This PR adds a few things that were missed in #48, namely:
- including the `dpr` parameter when generating a DPR srcset
- mentioning the use of `fit=crop` in documentation
- more test cases for DPR srcsets
- performance refactoring

fix: include dpr parameter when generating fixed-width srcset

---

README.md

As a follow up to #54, changes the pypi version badge.

docs: change pypi version badge

---

README.md

This PR serves as a follow up to #51, which converts the section subheaders to use the proper markdown style.

docs: modify subheaders to use markdown

---

.gitignore
.travis.yml
CONTRIBUTING.md
imgix/compat.py
imgix/urlbuilder.py
imgix/urlhelper.py
setup.py
tests/__init__.py
tests/test_url_builder.py
tests/test_url_helper.py
tox.ini

Fixes https://github.com/imgix/imgix-python/issues/40.
The issue was that [`compat.py`](https://github.com/imgix/imgix-python/blob/92509f246d489ac2896bd3b0ba981c6c66f7ac8d/imgix/compat.py) did not handle correctly all the edge cases around `urllib`. In addition to aliasing sub-modules, [`future`](https://python-future.org/standard_library_imports.html#aliased-imports) backports some `urllib` sub-modules so it can better deal with mixed encodings.
I had to refactor how the tests are setup in order to run them with and without the compatibility aliases. Due to how `pytest` share environments across tests, it was not possible to conditionally install the aliases on a per-test basis. Now all the tests, except for Flake8, will run in both regular and compatibility modes. This should prevent …

Fix Python 2/3 compatibility issues

---

README.md

While reading through the docs on [our site](https://docs.imgix.com/libraries/imgix-python) I noticed some single and double quotation characters were being escaped by backslashes.
This PR removes them.
The rendered markdown does not show these backslashes, but if you go to edit README.md you can see them.

docs: removes escaping backslash characters from readme

---

imgix/constants.py
imgix/validators.py
tests/test_validators.py
tox.ini

This commit introduces `validators.py`. It isn't a feature, it's a
utility. Abstracting validation out of individual files (where it
makes sense to) helps us validate and test better.
Instead of growing individual files with validation code,
`validators.py` can grow. It can grow so much that eventually
it could become
```text
validators
├── v0.py
└── v1.py
```
if necessary.
This commit is a part of my agenda to promote modularity and
plug-ability. These validators can be used and reused,
internally and externally.
This commit also defines the dependencies it needs:
```
INCREMENT_PERCENTAGE = 0.08
IMAGE_ZERO_WIDTH = 0.0
IMAGE_MIN_WIDTH = 100.0
IMAGE_MAX_WIDTH = 8192.0
```
They are additions to `SRCSET_MAX_SIZE` & `SRCSET_INCREMENT_PERCENTAGE`.
I've added constants rather than …

refactor: abstract validators

---

imgix/__init__.py

Cleans up artifacts of the `SIGNATURE_MODE` feature, which was deprecated/removed in #35.

chore: clean up remnant SIGNATURE_MODE artifacts

---

imgix/constants.py
imgix/urlbuilder.py
imgix/validators.py
tests/test_url_builder.py
tests/test_validators.py

The purpose of this PR is to implement custom srcset behavior by supporting:
* custom min and max widths
* custom width tolerance
This PR also seeks to do this without changing the public API.
This PR has been split into three commits:
* **validate min, max, and width tolerance**
* to call one validator instead of three
* test
* **implement custom target widths**
* pull target width generation into `UrlBuilder.py`
* this is where the validation occurs
* test
* **custom srcset widths and tolerance**
* validation is done here as well (so that `create_srcset` and `target_widths` can be used separately)
* extend the API to support custom srcset generation by specifying:
* custom min/max widths and 
* width tolerance.
Note: There have been 220 additions and 25 deletions here, however, more …

feat: create custom srcset

---

tests/test_url_builder.py

This PR changes a function's name to what it should be called.
From:
```python
test_target_widths_380_4088():
```
To:
```python
test_target_widths_328_4088():
```
No behavior has been changed. I noticed this while going over the
same kind of function in php. I guess I snuck this in; luckily, the
variable names hinted something was off.

refactor: correct test function name

---

imgix/urlbuilder.py

This PR removes a dead comment. Prior to this PR, the comment indicated
that there was validation, but validation was suggested to be, and was,
removed from this function. This change updates the comment to describe
the current behavior.

refactor: remove dead comment

---

imgix/urlbuilder.py

This PR documents the private function `_build_srcset_DPR`. I've opted
for regular comments over a docstring (per PEP8).

docs: describe behavior of _build_srcset_DPR

---

imgix/validators.py

This PR removes the word 'error' from these error messages.
While walking through some error states I noticed that these
error messages were a little redundant (i.e. python already
raises an `AssertionError` signaling the error state).
After this PR our error messages no longer reiterate that an
error state was encountered. Instead, they only indicate why
an error occurred.

refactor: remove redundant 'error' from error msgs

---

imgix/urlbuilder.py
imgix/validators.py
tests/test_url_builder.py
tests/test_validators.py

This PR seeks to normalize the behavior of target widths (kit wide).
Prior, it was an error to set `start = stop` when generating a range
of target width values. This has been relaxed and it is no longer an
error making generating target width lists of length 1 possible.

refactor: normalize behavior of target widths

---

imgix/constants.py
imgix/urlbuilder.py
tests/test_url_builder.py

The purpose of this PR is to remove the `ensure_even` requirement.
Previously, image target widths were required to be even integer values.
The original line of thought accounted for physical device pixel dimension
evenness; however, this is important only if images are rendered at full
viewport width.
Since this is not always the case, we wanted to include both odd and even
values here to give users more flexibility and to better meet user expectations:
i.e. if widths [115, …, 2121] were requested, then [116, …, 2122] could be
considered unexpected.
This PR also changes the default source set target widths; the values
have been updated to reflect the above changes. The values are also
assigned as a list (whereas assignment to `SRCSET_TARGET_WIDTHS`
was being done via function call).

refactor: remove ensure even

---

imgix/urlbuilder.py
tests/test_srcset.py

The purpose of this PR is to normalize feature behavior, specifically
custom srcset behavior.
Prior to this PR the `create_srcset` method accepted four key-worded
arguments. Now, those arguments have been replaced with `**kwargs`.
This PR also ensures that widths produced via `target_widths` are
`int` values to ensure that the list produced is a list of `int`s.
Four new tests have also been included. These tests ensure that
we are generating srcsets i.a.w. the rest of the SDK.

refactor: improve feature flexibility

---

README.md
imgix/__init__.py
tests/test_readme.py

This PR updates the readme for the custom srcsets feature set.
These changes not only reflect the **additional features** added, but
also try to pin down the **semantics** of our **syntax** and
documentation**.
Namely, the differentiation between `fixed` and `fluid-width` srcsets.
We currently construct two types of srcset attributes: those with `fixed`
widths and those with `fluid` widths.
**Fluid-widths vary**. A srcset attribute composed of target width pairs is
described as _fluid_ because each image candidate string denotes a
unique width-described resource.
**Fixed-widths are fixed**. A srcset attribute composed of pixel density
descriptors (ie. `1x, 2x, 3x`) is described as **fixed-width** because width
is held constant, while the pixel density descriptors vary.
Prior to this PR, …

docs(readme): update readme for custom srcset feat

---

README.md
imgix/constants.py
imgix/urlbuilder.py
imgix/validators.py
tests/test_readme.py
tests/test_srcset.py

Prior to this PR, width `tol`erance was expected to be of type `int`
and within the range of `[1, 100]` or "one to one hundred percent."
Now, `tol` is expected to be a `float` in the range `[0.01, 1.0]` which
also represents "one to one hundred percent."
We have done this for consistency purposes, i.e. [imgix-core-js](https://github.com/imgix/imgix-core-js/blob/2c9d97a7ab54c7a8fec378732bdcb855cef41907/src/imgix-core-js.js#L25) uses
floating point values. Since `imgix-core-js` was impl'd first, we defer
to this tried/tested interface. This way, this feature is standard
and consistent kit-wide.

refactor: convert tol to float

---

README.md

Fix small typo. This highlights the usefulness of doctests.

refactor: correct readme typo in srcset attr

---

imgix/errors.py
imgix/urlbuilder.py
imgix/validators.py
tests/test_srcset.py
tests/test_validators.py

The purpose of this PR is to complete our validation implementation.
The two exceptions used throughout this PR are:
- `WidthRangeError`: for invalid `start` or `stop` width values
- `WidthToleranceError`: for invalid width `tol`erance values.
An example of the output when an exception _is thrown_ is:
```python
from imgix import UrlBuilder
u = UrlBuilder("a.b.c", include_library_param=False)
u.create_srcset('image.png', start=1, stop=0)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "imgix-python/imgix/urlbuilder.py", line 191, in create_srcset
validate_min_max_tol(start, stop, tol)
File "imgix-python/imgix/validators.py", line 153, in validate_min_max_tol
validate_range(min_width, max_width)
File "imgix-python/imgix/validators.py", line 105, in validate_range …
```

refactor: throw exceptions from validators

---

imgix/validators.py
tests/test_validators.py

This PR relaxes the constraints on max width values. Prior to this PR
max width values were bounded, now they are not. The only restriction
is that image width values (both max and min) be greater than or equal
to zero (and that the max value is not less than the min value).

refactor: relax validation for max width values

---

README.md

shorten code examples to fit on docs pages

docs: shorten code examples to fit on docs pages

---

.travis.yml
tests/test_readme.py
tests/test_srcset.py
tests/test_url_builder.py
tests/test_url_helper.py
tests/test_validators.py

This PR disables the python versions where the builds are failing as a result of a version mismatch with `importlib_metadata`. This appears to be a python bug but further investigation is needed.
This PR also fixes style linting issues in the `/tests` directory with `flake8`.

ci: temp disable failing python versions

---

README.md
imgix/urlbuilder.py
tests/test_srcset.py
tests/test_url_builder.py

Before this PR, this library would encode all paths passed to either `create_url()` or `create_srcset()`. This was a great default in a lot of scenarios, but this proved to be irritating when integrating with some data sources that provided already encoded URL paths.
After this PR, the library would allow users to optionally pass a options parameter containing `disable_path_encoding` having boolean value.
* Testing the `create_url()` method
```python
>>> from imgix import UrlBuilder
>>> ub = UrlBuilder("sdk-test.imgix.net")
>>> ub.create_url(" <>[]{}|^%.jpg", params={'w': 100, 'h': 100}, options={'disable_path_encoding': True})  
'https://sdk-test.imgix.net/ <>[]{}|^%.jpg?h=100&w=100'
```
Normally this would output a source URL like …

feat: add functionality to optionally disable path encoding
